### ISSUE TITLE
Create a "stable" branch for use by docs and scripts

### ISSUE THREAD

**Issue by oubiwann** [lfe-deprecated/lfetool#114]
When the branch is created, the following tickets can use it and then be closed:
- #109 - Update project README and Quickstart with new download URL
- #113 - Update the "lfetool update" command to point to the right release

This need for this ticket was discussed in issue #111.

**Comment by dokkarr** [comment]
Proposal for branch re-org:
- create "stable" from branch "milestone-v1.2"
- create "dev-v1" from branch "milestone-v1.3" (merge to "stable" when milestone 1.3 is complete)
- create "dev-v2" from branch that is currently named "develop"

Other suggestions:
- make "stable" the default in the UI.
- document somewhere that "master" is really just another name for "legacy"; we could delete it once v3 is released ...
- clean up remaining branches (i.e., delete them)

**Comment by dokkarr** [comment]
This has been done, now:
- branches renamed
- v1.3 has been tagged and pushed, and merged to stable
- new milestone 1.4 has been created
- LFE 0.9.0 support tickets have been moved to milestone 1.4

More cleanup ahead, but will close.

Remaining tasks:
- update the version of dev-v1 to 1.4.0-dev
- update wiki pages and READMEs to point to stable instead of the old branches that they currently point to
- try to merge stable to dev-v2
- work on 1.4.0 to support LFE 0.9.0.
